config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/new'
  get 'todos/list'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'editar'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy', as: 'borrar'
  get 'todos/:id/complete', to: 'todos#complete', as: 'completar'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :find_todo, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @todos  = Todo.all
  end

  def list
    @todos  = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end

  def show
  end

  def edit
  end

  def update
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  def complete
    @todo.completed = true
    @todo.save
    redirect_to todos_path
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end

  def find_todo
    @todo = Todo.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

   <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

   <!-- Optional theme -->
   <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified JavaScript -->
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

    <style>
    	body{
    		margin: 0px auto;
    		padding-top: 10px;
    	}
      .seccion{
        padding: 50px;
      }
      .espacioTop{
    		padding-top: 20px;
    		margin-top: 100px;
    	}
    </style>

  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ToDo</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

            <li><%= link_to "Index", todos_path %></li>
            <li><%= link_to "Listado", todos_list_path %></li>
            <li><%= link_to "Crear ToDo", todos_new_path %></li>

          </ul>

          <ul class="nav navbar-nav navbar-right">

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>
  <%= f.label :description, "Description" %>
  <%= f.text_field :description %>

  <%= f.label :completed, "Completed" %>
  <%= f.check_box :completed %>

  <%= f.submit "Enviar" %>
<% end %>

app/views/todos/edit.html.erb
<%= render 'form' %>

app/views/todos/index.html.erb
<% @todos.each do |todo| %>

<div class="container well">
  <div class="row">
      <div class="col-md-4">
        <h1> <%= link_to todo.description, todo %></h1>
      </div>
      <div class="col-md-4">
        <h2> <%= todo.completed %></h2>
      </div>
      <div class="col-md-4">
        <%= link_to 'Editar', editar_path(todo) , class:'btn btn-success'%>
        <%= link_to 'Eliminar', borrar_path(todo), method: :delete, data: { confirm: 'Estas seguro de eliminar?' } , class:'btn btn-danger'%>
        <%= link_to 'Completar', completar_path(todo), class:'btn btn-success'%>
      </div>
  </div>
</div>
<% end %>

app/views/todos/list.html.erb
<div class="well">
    <div class="container seccion">
  		<div class="row">
  			<!--Primera Columna-->
  			<div class="col-md-6">
          <h1>Tareas completas</h1>
          <% @todos.each do |todo| %>
            <div class="container-fluid">
              <% if todo.completed %>
                <li><%= todo.description %></li>
              <% end %>
            </div>
          <% end %>
  			</div>
        <!--Segunda Columna-->
  			<div class="col-md-6">
          <h1>Tareas incompletas</h1>
          <% @todos.each do |todo| %>
            <div class="container-fluid">
              <% if !todo.completed %>
                <li><%= todo.description %></li>
              <% end %>
            </div>
          <% end %>
  			</div>
  		</div>
  	</div>
</div>

app/views/todos/new.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<h1> <%= @todo.description %></h1>
<p> <%= @todo.completed %></p>
<p> creado hace: <%= time_ago_in_words @todo.created_at %></p>
<%= link_to 'Volver', todos_path , class:'btn btn-info'%>